# BackBlaze B2 API credentials
# You will need to get these from the BackBlaze API Dashboard
[Account1]
  ACCOUNT_ID = "000"
  APPLICATION_ID = "000"
  API_URL = "https://api.backblazeb2.com/b2api/v1/b2_authorize_account"
